import { storage } from './storage';
import { getArticleImage } from './utils/imageMapping';
import type { InsertArticle } from '@shared/schema';

// Indian news source URLs to distribute equally among articles
const indianNewsSourceUrls = [
  'https://www.thehindu.com',
  'https://www.ndtv.com', 
  'https://indianexpress.com',
  'https://www.business-standard.com'
];

const getDistributedSourceUrl = (index: number): string => {
  return indianNewsSourceUrls[index % indianNewsSourceUrls.length];
};

const sampleArticles: InsertArticle[] = [
  {
    title: "India's AI Revolution: New Tech Hub Opens in Bengaluru",
    content: "In a major boost to India's tech ecosystem, a state-of-the-art AI research center has been inaugurated in Bengaluru. Designed to foster innovation and deep learning research, the facility is projected to generate over 2,000 jobs. \"This marks a new era for India's digital leadership,\" said the IT minister. Experts view it as a step toward positioning India as a global AI hub.",
    summary: "New AI Research Center Expected to Create 2,000 Jobs",
    url: getDistributedSourceUrl(0),
    imageUrl: getArticleImage("technology", "India's AI Revolution: New Tech Hub Opens in Bengaluru", "In a major boost to India's tech ecosystem, a state-of-the-art AI research center has been inaugurated in Bengaluru"),
    source: "Tech Today India",
    author: "Priya Sharma",
    category: "technology",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Healthcare Goes Digital: India Launches National Telemedicine Grid",
    content: "To bridge the healthcare divide in rural India, the Health Ministry has launched a national telemedicine grid connecting over 10,000 public hospitals. The grid uses AI to assist diagnosis and automate appointment systems. \"This ensures rural patients can consult top urban doctors,\" said the Health Secretary. While critics warn of digital literacy gaps, the initiative is being hailed as a healthcare game changer.",
    summary: "Government Connects 10,000 Hospitals Through AI-Powered Grid",
    url: getDistributedSourceUrl(1),
    imageUrl: getArticleImage("health", "Healthcare Goes Digital: India Launches National Telemedicine Grid", "telemedicine grid connecting over 10,000 public hospitals"),
    source: "Health India Today",
    author: "Dr. Meera Singh",
    category: "health",
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.5,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Political Reforms: Electoral Bonds Scrapped by Supreme Court",
    content: "In a historic judgment, the Supreme Court ruled electoral bonds unconstitutional, citing lack of transparency in political funding. Activists celebrated the decision, calling it a win for democracy. While government sources expressed disappointment, they assured compliance. Analysts predict the verdict could alter campaign finance structures before the 2029 elections.",
    summary: "Court Declares Electoral Bonds Unconstitutional",
    url: getDistributedSourceUrl(2),
    imageUrl: "https://images.unsplash.com/photo-1586880244386-8b3e34d8b844?w=400",
    source: "Political Daily",
    author: "Ramesh Gupta",
    category: "politics",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.3,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "India to Regulate Generative AI",
    content: "Concerned with misinformation, the Indian government is drafting a bill to regulate generative AI. The law mandates developers to register large language models and conduct fairness audits. Proponents applaud the ethical approach; critics fear it may hinder startups. \"AI must evolve responsibly,\" said an IT ministry spokesperson.",
    summary: "Draft Bill Proposes Registration for AI Models and Bias Audits",
    url: getDistributedSourceUrl(3),
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400",
    source: "Tech Regulatory News",
    author: "Arjun Patel",
    category: "technology",
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.1,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "Women's IPL Breaks Viewership Record",
    content: "The Women's IPL 2025 finals saw a record-breaking 60 million viewers. Mumbai Blaze triumphed over Delhi Queens in a nail-biting thriller. Social media trended #HerGameToo as fans flooded platforms with praise. Experts say this signals a massive cultural shift in gender equality within Indian sports.",
    summary: "WIPL 2025 Finals Draw 60 Million Live Viewers",
    url: getDistributedSourceUrl(4),
    imageUrl: getArticleImage("sports", "Women's IPL Breaks Viewership Record", "The Women's IPL 2025 finals saw a record-breaking 60 million viewers. Mumbai Blaze triumphed over Delhi Queens"),
    source: "Sports Central",
    author: "Anil Mehta",
    category: "sports",
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "ISRO Successfully Tests Reusable Rocket Booster",
    content: "ISRO has successfully tested a reusable booster prototype for future space launches. The innovation is expected to cut costs by 60% and position India competitively in the global satellite market. \"Our goal is sustainability and affordability in space tech,\" said an ISRO official. Global space agencies took note, calling it a \"remarkable leap.\"",
    summary: "India's Space Program Eyes Low-Cost Satellite Launches",
    url: getDistributedSourceUrl(5),
    imageUrl: getArticleImage("technology", "ISRO Successfully Tests Reusable Rocket Booster", "ISRO has successfully tested a reusable booster prototype for future space launches"),
    source: "Space News India",
    author: "Dr. Vikram Sarabhai",
    category: "technology",
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Government Cuts Corporate Taxes to Attract Investment",
    content: "In a move to boost India's business environment, the finance ministry has slashed corporate tax rates to 20%. Industry leaders say it could make India a global manufacturing hub. Economists warn of short-term revenue losses.",
    summary: "Budget 2025 Offers Corporate Tax Relief",
    url: getDistributedSourceUrl(6),
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400",
    source: "Economic Times",
    author: "Sunita Patel",
    category: "finance",
    publishedAt: new Date(Date.now() - 14 * 60 * 60 * 1000),
    politicalBias: "right",
    biasConfidence: 0.6,
    sentimentScore: 0.6,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Govt Expands Healthcare Scheme to Record Levels",
    content: "Ayushman Bharat, India's flagship health scheme, now extends to over 60 crore people. Officials say it provides free treatment in over 24,000 hospitals. Critics urge better implementation and fraud prevention.",
    summary: "Ayushman Bharat Now Covers 60 Crore Citizens",
    url: getDistributedSourceUrl(7),
    imageUrl: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    source: "Health India Today",
    author: "Dr. Kavita Singh",
    category: "health",
    publishedAt: new Date(Date.now() - 16 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.5,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Indian Women's Cricket Team Wins Asia Cup",
    content: "The Indian women's team lifted the Asia Cup after defeating Sri Lanka in the finals. The victory drew praise from across the country, with special mention of young talents who stepped up under pressure.",
    summary: "India Clinches Another Title in Women's Cricket",
    url: getDistributedSourceUrl(8),
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400",
    source: "Cricket Today",
    author: "Priya Kumari",
    category: "sports",
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "ISRO Unveils NavIC for Civilian Use",
    content: "ISRO has launched the civilian version of NavIC, India's own GPS alternative. It promises better accuracy across Indian territory. Experts call it a step toward technological sovereignty and better disaster response capabilities.",
    summary: "India Launches Indigenous Navigation System",
    url: getDistributedSourceUrl(9),
    imageUrl: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?w=400",
    source: "Tech Today India",
    author: "Kiran Rao",
    category: "technology",
    publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.6,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "भारत में बनी सस्ती सौर टेक्नोलॉजी को अफ्रीका में अपनाया गया",
    content: "भारत की लो-कॉस्ट सोलर टेक्नोलॉजी अब अफ्रीकी देशों में अपनाई जा रही है। इस तकनीक से ग्रामीण क्षेत्रों में बिजली पहुँचना शुरू हो गया है। \"भारत का मॉडल टिकाऊ और किफायती है,\" एक अफ्रीकी मंत्री ने कहा।",
    summary: "भारतीय सोलर पैनल तकनीक ने अफ्रीका में ऊर्जा क्रांति लाई",
    url: getDistributedSourceUrl(10),
    imageUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400",
    source: "Bharat Today",
    author: "संजय शर्मा",
    category: "general",
    publishedAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Government to Set Up 100 New Skill Centers",
    content: "The Ministry of Skill Development has announced the launch of 100 new skill centers across rural India. These centers will focus on emerging technologies like AI, robotics, and green energy to empower youth.",
    summary: "Major Push for Vocational Education",
    url: getDistributedSourceUrl(11),
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400",
    source: "Education News",
    author: "Meera Patel",
    category: "general",
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.6,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "विश्व योग दिवस पर 12 करोड़ लोगों ने लिया भाग",
    content: "प्रधानमंत्री के नेतृत्व में अंतरराष्ट्रीय योग दिवस पर देशभर में करोड़ों लोगों ने भाग लिया। कार्यक्रमों का आयोजन 100 से अधिक देशों में हुआ। सरकार ने इसे भारत की 'सॉफ्ट पावर' की जीत बताया।",
    summary: "योग से जुड़ा सबसे बड़ा वैश्विक आयोजन",
    url: getDistributedSourceUrl(12),
    imageUrl: getArticleImage("general", "विश्व योग दिवस पर 12 करोड़ लोगों ने लिया भाग", "प्रधानमंत्री के नेतृत्व में अंतरराष्ट्रीय योग दिवस पर देशभर में करोड़ों लोगों ने भाग लिया"),
    source: "Yoga Times",
    author: "राम कुमार",
    category: "general",
    publishedAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "भारतीय रेलवे ने शुरू की हाइड्रोजन ट्रेन परियोजना",
    content: "भारतीय रेलवे ने पर्यावरण को ध्यान में रखते हुए हाइड्रोजन से चलने वाली ट्रेनें शुरू करने की घोषणा की है। यह परियोजना देश की कार्बन उत्सर्जन को कम करने की दिशा में बड़ा कदम मानी जा रही है।",
    summary: "रेलवे में हाइड्रोजन से चलने वाली ट्रेनों की योजना",
    url: getDistributedSourceUrl(13),
    imageUrl: getArticleImage("technology", "भारतीय रेलवे ने शुरू की हाइड्रोजन ट्रेन परियोजना", "भारतीय रेलवे ने पर्यावरण को ध्यान में रखते हुए हाइड्रोजन से चलने वाली ट्रेनें शुरू करने की घोषणा की है"),
    source: "Rail News India",
    author: "विजय सिंह",
    category: "technology",
    publishedAt: new Date(Date.now() - 28 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  
  // New 25 articles from attachment
  {
    title: "Parliament Passes Data Protection Bill",
    content: "India's new Digital Personal Data Protection (DPDP) Bill requires companies and government entities to seek explicit consent before collecting or processing personal data. It introduces the Data Protection Board of India, responsible for investigating violations and levying penalties. Critics argue that some government exemptions undermine the bill's effectiveness, but digital rights groups still consider it a step forward.",
    summary: "New data protection law requires explicit consent for data collection",
    url: getDistributedSourceUrl(14),
    imageUrl: getArticleImage("politics", "Parliament Passes Data Protection Bill", "India's new Digital Personal Data Protection (DPDP) Bill requires companies and government entities to seek explicit consent"),
    source: "Legal Today",
    author: "Adv. Priya Sharma",
    category: "politics",
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    politicalBias: "left",
    biasConfidence: 0.7,
    sentimentScore: 0.4,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "Nationwide Mental Health Helpline Launched",
    content: "With suicide and stress-related issues on the rise, India launched Tele-MANAS, a 24/7 mental health helpline. Operating in 22+ languages and staffed by psychologists and psychiatrists, it has already handled over 3 million calls since its beta launch. The initiative was praised for bridging rural mental health gaps.",
    summary: "Tele-MANAS helpline addresses mental health crisis nationwide",
    url: getDistributedSourceUrl(15),
    imageUrl: getArticleImage("health", "Nationwide Mental Health Helpline Launched", "India launched Tele-MANAS, a 24/7 mental health helpline"),
    source: "Health India Today",
    author: "Dr. Kavita Singh",
    category: "health",
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Government Approves Drone Corridors",
    content: "India cleared specific drone air routes for logistics, agriculture spraying, and vaccine delivery. The DGCA and MoCA will regulate these corridors. These are expected to revolutionize remote healthcare access but also raised questions about air safety and job losses in manual logistics.",
    summary: "New drone corridors approved for logistics and healthcare delivery",
    url: getDistributedSourceUrl(16),
    imageUrl: getArticleImage("technology", "Government Approves Drone Corridors", "India cleared specific drone air routes for logistics, agriculture spraying, and vaccine delivery"),
    source: "Tech Today India",
    author: "Arjun Patel",
    category: "technology",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    politicalBias: "right",
    biasConfidence: 0.6,
    sentimentScore: 0.3,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "RBI Pilots Digital Rupee Wallet",
    content: "The e₹-R wallet pilot supports offline transactions, tap-to-pay options, and banking access for those in network-poor areas. It offers an alternative to private digital currencies and may lower transaction costs. Privacy advocates have raised surveillance concerns.",
    summary: "Digital rupee pilot program launches with offline transaction capability",
    url: getDistributedSourceUrl(17),
    imageUrl: getArticleImage("finance", "RBI Pilots Digital Rupee Wallet", "The e₹-R wallet pilot supports offline transactions, tap-to-pay options"),
    source: "Economic Times",
    author: "Sunita Patel",
    category: "finance",
    publishedAt: new Date(Date.now() - 7 * 60 * 60 * 1000),
    politicalBias: "right",
    biasConfidence: 0.7,
    sentimentScore: 0.2,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "Solar Startup Raises $100M",
    content: "EcoSun has raised funds to install solar rooftops across public buildings, starting with schools and health centers in low-income areas. It will also provide maintenance via a mobile app and offers students energy dashboards to learn about renewables.",
    summary: "EcoSun secures funding for solar rooftop installations in public buildings",
    url: getDistributedSourceUrl(18),
    imageUrl: getArticleImage("technology", "Solar Startup Raises $100M", "EcoSun has raised funds to install solar rooftops across public buildings"),
    source: "Green Tech News",
    author: "Kiran Rao",
    category: "technology",
    publishedAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.9,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Ayushman Bharat to Cover Cancer",
    content: "The scheme now covers free cancer screening and treatment at 1,000+ hospitals, including surgery and chemo. The government aims to cut early mortality rates from breast and oral cancer in rural India by 50% by 2030.",
    summary: "Healthcare scheme expands to cover comprehensive cancer treatment",
    url: getDistributedSourceUrl(19),
    imageUrl: getArticleImage("health", "Ayushman Bharat to Cover Cancer", "The scheme now covers free cancer screening and treatment at 1,000+ hospitals"),
    source: "Health India Today",
    author: "Dr. Meera Singh",
    category: "health",
    publishedAt: new Date(Date.now() - 11 * 60 * 60 * 1000),
    politicalBias: "left",
    biasConfidence: 0.7,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "AI Ethics Centre in Chennai",
    content: "India's first AI Ethics hub will audit public sector AI projects, publish bias reports, and train officials. Backed by IIT Madras and MIT, it aims to align AI development with privacy and social impact goals.",
    summary: "First AI Ethics center established to monitor government AI projects",
    url: getDistributedSourceUrl(20),
    imageUrl: getArticleImage("technology", "AI Ethics Centre in Chennai", "India's first AI Ethics hub will audit public sector AI projects"),
    source: "Tech Today India",
    author: "Dr. Vikram Sarabhai",
    category: "technology",
    publishedAt: new Date(Date.now() - 13 * 60 * 60 * 1000),
    politicalBias: "left",
    biasConfidence: 0.8,
    sentimentScore: 0.6,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Quantum Satellite by 2026",
    content: "ISRO is working with DRDO to launch India's first quantum encryption satellite, which could make military and government comms impossible to hack. This is part of India's larger Quantum Mission with ₹6,000 crore in funding.",
    summary: "ISRO plans quantum encryption satellite for secure communications",
    url: getDistributedSourceUrl(21),
    imageUrl: getArticleImage("technology", "Quantum Satellite by 2026", "ISRO is working with DRDO to launch India's first quantum encryption satellite"),
    source: "Space News India",
    author: "Kiran Rao",
    category: "technology",
    publishedAt: new Date(Date.now() - 15 * 60 * 60 * 1000),
    politicalBias: "right",
    biasConfidence: 0.7,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Fintech Sandbox Opens",
    content: "Fintech startups can test their platforms—e.g., AI-driven credit, P2P lending—under RBI supervision. This avoids licensing delays while keeping consumers protected. Global VC interest is rising in the sandbox ecosystem.",
    summary: "RBI launches regulatory sandbox for fintech innovation",
    url: getDistributedSourceUrl(22),
    imageUrl: getArticleImage("finance", "Fintech Sandbox Opens", "Fintech startups can test their platforms under RBI supervision"),
    source: "Economic Times",
    author: "Sunita Patel",
    category: "finance",
    publishedAt: new Date(Date.now() - 17 * 60 * 60 * 1000),
    politicalBias: "right",
    biasConfidence: 0.6,
    sentimentScore: 0.5,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "UPI Goes Live in Bhutan",
    content: "Indian travelers and Bhutanese merchants can now use UPI for instant cross-border payments. It symbolizes strong regional ties and simplifies commerce in areas with low card penetration.",
    summary: "UPI payment system extends to Bhutan for cross-border transactions",
    url: getDistributedSourceUrl(23),
    imageUrl: getArticleImage("finance", "UPI Goes Live in Bhutan", "Indian travelers and Bhutanese merchants can now use UPI for instant cross-border payments"),
    source: "Economic Times",
    author: "Ramesh Gupta",
    category: "finance",
    publishedAt: new Date(Date.now() - 19 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Railways Wi-Fi Expansion",
    content: "Free public Wi‑Fi across 400+ Indian Railway stations aims to provide education and digital access to rural commuters. RailTel handles backend integration with Google, who provides analytics.",
    summary: "Free Wi-Fi service expands to 400+ railway stations nationwide",
    url: getDistributedSourceUrl(24),
    imageUrl: getArticleImage("technology", "Railways Wi-Fi Expansion", "Free public Wi‑Fi across 400+ Indian Railway stations"),
    source: "Rail News India",
    author: "विजय सिंह",
    category: "technology",
    publishedAt: new Date(Date.now() - 21 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "India in Paris Olympics Chess",
    content: "After decades of absence, India qualifies for chess at the Olympics, powered by teen prodigies like Praggnanandhaa and Vaishali. The team ranks top-4 globally in performance metrics.",
    summary: "Indian chess team qualifies for Olympics after decades",
    url: getDistributedSourceUrl(25),
    imageUrl: getArticleImage("sports", "India in Paris Olympics Chess", "India qualifies for chess at the Olympics, powered by teen prodigies"),
    source: "Sports Central",
    author: "Anil Mehta",
    category: "sports",
    publishedAt: new Date(Date.now() - 23 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.9,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "PHCs Go Fully Digital",
    content: "All PHCs must adopt ABHA-linked Electronic Health Records by 2026. This includes QR-coded reports, teleconsultation support, and referral history. Experts warn smaller PHCs may lack tech capacity.",
    summary: "Primary Health Centers to implement digital health records by 2026",
    url: getDistributedSourceUrl(26),
    imageUrl: getArticleImage("health", "PHCs Go Fully Digital", "All PHCs must adopt ABHA-linked Electronic Health Records by 2026"),
    source: "Health India Today",
    author: "Dr. Kavita Singh",
    category: "health",
    publishedAt: new Date(Date.now() - 25 * 60 * 60 * 1000),
    politicalBias: "left",
    biasConfidence: 0.7,
    sentimentScore: 0.4,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "Bharat Startup Mela",
    content: "An event in Lucknow will host 5,000+ startups, 50 VC firms, and government accelerators. It emphasizes non-metro innovation and includes a separate track for women founders and SC/ST entrepreneurs.",
    summary: "Lucknow hosts major startup event focusing on non-metro innovation",
    url: getDistributedSourceUrl(27),
    imageUrl: getArticleImage("general", "Bharat Startup Mela", "An event in Lucknow will host 5,000+ startups, 50 VC firms"),
    source: "Business Standard",
    author: "Meera Patel",
    category: "general",
    publishedAt: new Date(Date.now() - 27 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "Kerala Women Win Asia Cup",
    content: "Led by Kerala's Anju K. Thomas, India beat Japan in a dramatic 2-1 comeback. The match broke viewership records on DD Sports and led to a 30% increase in girl football enrollments in Kerala.",
    summary: "Indian women's football team wins Asia Cup in dramatic comeback",
    url: getDistributedSourceUrl(28),
    imageUrl: getArticleImage("sports", "Kerala Women Win Asia Cup", "Led by Kerala's Anju K. Thomas, India beat Japan in a dramatic 2-1 comeback"),
    source: "Sports Central",
    author: "Priya Kumari",
    category: "sports",
    publishedAt: new Date(Date.now() - 29 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.9,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  
  // Hindi Articles (5)
  {
    title: "महिला आरक्षण विधेयक पेश",
    content: "33% आरक्षण के लिए लाया गया विधेयक 2026 से प्रभावी होगा। इससे लोकसभा और राज्य विधानसभाओं में महिलाओं की भागीदारी बढ़ेगी। कुछ पार्टियों ने इसे चुनावी स्टंट बताया।",
    summary: "महिलाओं के लिए 33% आरक्षण विधेयक 2026 से लागू होगा",
    url: getDistributedSourceUrl(29),
    imageUrl: getArticleImage("politics", "महिला आरक्षण विधेयक पेश", "33% आरक्षण के लिए लाया गया विधेयक 2026 से प्रभावी होगा"),
    source: "Political Daily",
    author: "राम कुमार",
    category: "politics",
    publishedAt: new Date(Date.now() - 31 * 60 * 60 * 1000),
    politicalBias: "left",
    biasConfidence: 0.7,
    sentimentScore: 0.6,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "यूपी में मुफ्त स्वास्थ्य शिविर",
    content: "राज्य सरकार ने प्रत्येक जिले में हफ्ते में दो बार कैंसर, मधुमेह और टीबी जांच कैंप लगाए हैं। इसमें मुफ्त दवाएं, ECG, और अल्ट्रासाउंड सुविधाएं शामिल हैं।",
    summary: "यूपी में साप्ताहिक मुफ्त स्वास्थ्य जांच शिविर शुरू",
    url: getDistributedSourceUrl(30),
    imageUrl: getArticleImage("health", "यूपी में मुफ्त स्वास्थ्य शिविर", "राज्य सरकार ने प्रत्येक जिले में हफ्ते में दो बार कैंसर, मधुमेह और टीबी जांच कैंप"),
    source: "Health India Today",
    author: "डॉ. मीरा सिंह",
    category: "health",
    publishedAt: new Date(Date.now() - 33 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "कार्बन क्रेडिट एक्सचेंज शुरू",
    content: "यह एक्सचेंज इंडस्ट्रीज़ को स्वच्छ ऊर्जा खरीदने या उत्सर्जन घटाने के लिए वित्तीय लाभ देगा। इससे ग्रीन प्रोजेक्ट्स को पूंजी मिलेगी, पर कुछ विशेषज्ञों ने पारदर्शिता पर सवाल उठाए हैं।",
    summary: "भारत में कार्बन क्रेडिट एक्सचेंज की शुरुआत",
    url: getDistributedSourceUrl(31),
    imageUrl: getArticleImage("finance", "कार्बन क्रेडिट एक्सचेंज शुरू", "यह एक्सचेंज इंडस्ट्रीज़ को स्वच्छ ऊर्जा खरीदने या उत्सर्जन घटाने के लिए वित्तीय लाभ देगा"),
    source: "Economic Times",
    author: "सुनीता पटेल",
    category: "finance",
    publishedAt: new Date(Date.now() - 35 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.5,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "मुंबई में EV चार्जिंग नेटवर्क",
    content: "BMC ने मॉल, बस स्टॉप और सरकारी कार्यालयों में 1,000 चार्जिंग स्टेशन की योजना बनाई है। उपयोगकर्ताओं को 50 रुपये प्रति चार्जिंग का मानक शुल्क देना होगा।",
    summary: "मुंबई में 1,000 EV चार्जिंग स्टेशन की योजना",
    url: getDistributedSourceUrl(32),
    imageUrl: getArticleImage("technology", "मुंबई में EV चार्जिंग नेटवर्क", "BMC ने मॉल, बस स्टॉप और सरकारी कार्यालयों में 1,000 चार्जिंग स्टेशन की योजना"),
    source: "Tech Today India",
    author: "अर्जुन पटेल",
    category: "technology",
    publishedAt: new Date(Date.now() - 37 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "महिला हॉकी टीम की ऐतिहासिक जीत",
    content: "टीम ने एशिया कप में जापान को हराया, और अब पेरिस ओलंपिक्स की तैयारी कर रही है। सरकार ने खिलाड़ियों को ₹15 लाख इनाम देने की घोषणा की है।",
    summary: "भारतीय महिला हॉकी टीम ने एशिया कप जीता",
    url: getDistributedSourceUrl(33),
    imageUrl: getArticleImage("sports", "महिला हॉकी टीम की ऐतिहासिक जीत", "टीम ने एशिया कप में जापान को हराया"),
    source: "Sports Central",
    author: "प्रिया कुमारी",
    category: "sports",
    publishedAt: new Date(Date.now() - 39 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.9,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  
  // Marathi Articles (5)
  {
    title: "कृषी कायदे मंजूर",
    content: "नवीन कायद्यांनुसार शेतकऱ्यांना खुल्या बाजारात विक्रीची मुभा मिळणार आहे. संघटनांनी याचे स्वागत केले, तर विरोधकांनी MSP सुनिश्चितीवर चिंता व्यक्त केली.",
    summary: "शेतकऱ्यांना खुल्या बाजारात विक्री करण्याची परवानगी",
    url: getDistributedSourceUrl(34),
    imageUrl: getArticleImage("politics", "कृषी कायदे मंजूर", "नवीन कायद्यांनुसार शेतकऱ्यांना खुल्या बाजारात विक्रीची मुभा मिळणार आहे"),
    source: "Maharashtra Times",
    author: "संजय शर्मा",
    category: "politics",
    publishedAt: new Date(Date.now() - 41 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.7,
    sentimentScore: 0.4,
    emotionalTone: "neutral",
    availableLanguages: [],
  },
  {
    title: "पुण्यात डेंगू तपासणी",
    content: "महापालिकेच्या आरोग्य विभागाने प्रत्येक झोनमध्ये आठवड्यातून दोन वेळा मोफत तपासणी सुरू केली. नागरिकांना कीटकनाशके व आरोग्य किटही दिले जात आहे.",
    summary: "पुण्यात मोफत डेंगू तपासणी मोहीम सुरू",
    url: getDistributedSourceUrl(35),
    imageUrl: getArticleImage("health", "पुण्यात डेंगू तपासणी", "महापालिकेच्या आरोग्य विभागाने प्रत्येक झोनमध्ये आठवड्यातून दोन वेळा मोफत तपासणी सुरू केली"),
    source: "Pune Mirror",
    author: "डॉ. विकास पाटील",
    category: "health",
    publishedAt: new Date(Date.now() - 43 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.7,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "AI पाणी प्रणाली",
    content: "स्मार्ट मीटर प्रणाली सुरू करण्यात आली असून, नागरिकांना SMS द्वारे वापर माहिती दिली जाईल. हे महाराष्ट्रातील पहिले पूर्णपणे AI-विनियंत्रित वॉटर ग्रिड ठरेल.",
    summary: "महाराष्ट्रात AI-आधारित स्मार्ट वॉटर ग्रिड सुरू",
    url: getDistributedSourceUrl(36),
    imageUrl: getArticleImage("technology", "AI पाणी प्रणाली", "स्मार्ट मीटर प्रणाली सुरू करण्यात आली असून, नागरिकांना SMS द्वारे वापर माहिती दिली जाईल"),
    source: "Tech Maharashtra",
    author: "अर्जुन देशमुख",
    category: "technology",
    publishedAt: new Date(Date.now() - 45 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.8,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "कोळीकर महोत्सव",
    content: "पुण्यात होणाऱ्या उत्सवात 30+ कोळी कला सादर होतील. सांस्कृतिक मंत्रालयाने ₹25 लाख निधी मंजूर केला असून, पर्यटन वाढीस देखील मदत होईल.",
    summary: "पुण्यात कोळी कलेचा मोठा उत्सव आयोजित",
    url: getDistributedSourceUrl(37),
    imageUrl: getArticleImage("general", "कोळीकर महोत्सव", "पुण्यात होणाऱ्या उत्सवात 30+ कोळी कला सादर होतील"),
    source: "Maharashtra Times",
    author: "प्रिया जोशी",
    category: "general",
    publishedAt: new Date(Date.now() - 47 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.8,
    emotionalTone: "positive",
    availableLanguages: [],
  },
  {
    title: "मुलींसाठी क्रिकेट शिबिर",
    content: "मुंबईत 500 मुलींसाठी क्रिकेट प्रशिक्षण सुरू आहे. यामध्ये BCCI प्रशिक्षकांद्वारे कोचिंग दिले जात असून, जिल्हा पातळीवरील स्पर्धेसाठी निवड प्रक्रिया सुरू आहे.",
    summary: "मुंबईत 500 मुलींसाठी क्रिकेट प्रशिक्षण शिबिर",
    url: getDistributedSourceUrl(38),
    imageUrl: getArticleImage("sports", "मुलींसाठी क्रिकेट शिबिर", "मुंबईत 500 मुलींसाठी क्रिकेट प्रशिक्षण सुरू आहे"),
    source: "Sports Maharashtra",
    author: "रुपाली पाटील",
    category: "sports",
    publishedAt: new Date(Date.now() - 49 * 60 * 60 * 1000),
    politicalBias: "neutral",
    biasConfidence: 0.9,
    sentimentScore: 0.9,
    emotionalTone: "positive",
    availableLanguages: [],
  }
];

export async function initializeSampleData(): Promise<void> {
  try {
    // Check if we already have the new articles (count should be 39 total: 14 original + 25 new)
    const existingArticles = await storage.getArticles({ language: 'en' });
    if (existingArticles.length >= 39) {
      console.log('Sample data with new articles already exists, skipping initialization');
      return;
    }

    // Clear existing data and add all sample articles (including new 25)
    console.log('Initializing with updated sample data including 25 new articles...');
    
    // Add sample articles and create translations for the first few English articles
    for (let i = 0; i < sampleArticles.length; i++) {
      const articleData = sampleArticles[i];
      const createdArticle = await storage.createArticle(articleData);
      
      // Add sample translations for the first 5 English articles to demonstrate language sync
      if (i < 5 && createdArticle.category !== 'hindi' && createdArticle.category !== 'marathi') {
        // Hindi translations
        await storage.createTranslation({
          articleId: createdArticle.id,
          language: 'hi',
          translatedTitle: getHindiTitle(createdArticle.title),
          translatedContent: `[हिंदी में अनुवादित] ${createdArticle.content}`,
          translatedSummary: createdArticle.summary ? `[हिंदी] ${createdArticle.summary}` : null
        });

        // Marathi translations
        await storage.createTranslation({
          articleId: createdArticle.id,
          language: 'mr',
          translatedTitle: getMarathiTitle(createdArticle.title),
          translatedContent: `[मराठीत अनुवादित] ${createdArticle.content}`,
          translatedSummary: createdArticle.summary ? `[मराठी] ${createdArticle.summary}` : null
        });
      }
    }

    console.log(`Successfully initialized ${sampleArticles.length} sample articles (including 25 new articles) with sample translations`);
  } catch (error) {
    console.error('Error initializing sample data:', error);
  }
}

function getHindiTitle(englishTitle: string): string {
  const titleMap: { [key: string]: string } = {
    "India's AI Revolution: New Tech Hub Opens in Bengaluru": "भारत की AI क्रांति: बेंगलुरु में नया टेक हब खुला",
    "Healthcare Goes Digital: India Launches National Telemedicine Grid": "स्वास्थ्य सेवा डिजिटल हुई: भारत ने राष्ट्रीय टेलीमेडिसिन ग्रिड लॉन्च किया",
    "Political Reforms: Electoral Bonds Scrapped by Supreme Court": "राजनीतिक सुधार: सुप्रीम कोर्ट ने इलेक्टोरल बॉन्ड रद्द किए",
    "India to Regulate Generative AI": "भारत जेनरेटिव AI को नियंत्रित करेगा",
    "ISRO Unveils NavIC for Civilian Use": "इसरो ने नागरिक उपयोग के लिए NavIC का अनावरण किया"
  };
  return titleMap[englishTitle] || `[हिंदी] ${englishTitle}`;
}

function getMarathiTitle(englishTitle: string): string {
  const titleMap: { [key: string]: string } = {
    "India's AI Revolution: New Tech Hub Opens in Bengaluru": "भारताची AI क्रांती: बेंगलुरुमध्ये नवा टेक हब उघडला",
    "Healthcare Goes Digital: India Launches National Telemedicine Grid": "आरोग्य सेवा डिजिटल झाली: भारताने राष्ट्रीय टेलीमेडिसिन ग्रिड लॉन्च केले",
    "Political Reforms: Electoral Bonds Scrapped by Supreme Court": "राजकीय सुधारणा: सर्वोच्च न्यायालयाने इलेक्टोरल बॉन्ड रद्द केले",
    "India to Regulate Generative AI": "भारत जेनरेटिव्ह AI नियंत्रित करणार",
    "ISRO Unveils NavIC for Civilian Use": "इस्रोने नागरी वापरासाठी NavIC चे अनावरण केले"
  };
  return titleMap[englishTitle] || `[मराठी] ${englishTitle}`;
}